# Generated by Django 2.2.5 on 2019-09-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190916_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('payment', models.CharField(max_length=50, verbose_name='Meio Pagamento')),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
